export const TEXT = {
  WELCOME_MSG: 'Welcome..!',
  SIGNIN: 'SignIn',
  SIGNUP: 'SignUp',
  GOOGLESIGNIN: 'Sign in with Google',
  EMAIL: 'Enter Your Email',
  EMAIL_LABEL: 'EMAIL',
  PASSWORD: 'Enter Your Password',
  PASSWORD_LABEL: 'PASSWORD',
  REGISTER: 'Register',
  CONFIRM_PASSWORD: 'Enter Confirm Password',
  CONFIRM_PASSWORD_LABEL: 'CONFIRM PASSWORD',
  USERNAME_LABEL: 'USERNAME',
  USERNAME: 'Enter Your Username',
  VALID_EMAIL_ERROR_TEXT: 'Enter Valid Email Id',
  USER_NOT_FOUND: 'User not found',
  INVALID_PASSWORD: 'Invalid Password',
  INVALID_USER: 'Invalid Email',
  VALID_PASSWORD_ERROR_TEXT: 'Enter Valid Password',
};
